name: "cloud: tier 1: up"
on:
  push:
    branches:
      - "main"
    paths:
      - cloud/**
permissions:
  pull-requests: write
  contents: read
defaults:
  run:
    working-directory: cloud/
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: sleep 10 && echo "Hello World!"
