name: "tier 2 up"
on:
  workflow_run:
    workflows:
      - "tier 1 up"
    branches:
      - main
    types:
      - completed
permissions:
  pull-requests: write
  contents: read
jobs:
  hello-world:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
